[[plugins]] # neocomplete
repo = 'Shougo/neocomplete.vim'
hook_add = '''
  let g:acp_enableAtStartup = 0
  let g:neocomplete#enable_at_startup = 1
  let g:neocomplete#enable_smart_case = 1

  if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
  endif
  let g:neocomplete#force_omni_input_patterns.ruby = '[^.*\t]\.\w*\|\h\w*::'

  autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete

  if !exists('g:neocomplete#force_omni_input_patterns')
    let g:neocomplete#force_omni_input_patterns = {}
  endif
  let g:neocomplete#force_omni_input_patterns.ruby =
        \'[^. *\t]\.\w*\|\h\w*::'

  if !exists('g:neocomplete#sources#omni#input_patterns')
    let g:neocomplete#sources#omni#input_patterns = {}
  endif
'''

[[plugins]] # neosnippet
repo = 'Shougo/neosnippet'
hook_add = '''
  let g:neosnippet#enable_snipmate_compatibility = 1 " Enable snipMate compatibility feature.
  let g:neosnippet#snippets_directory='~/.vim/bundle/snipmate-snippets' " Tell Neosnippet about the other snippets
'''

[[plugins]] # neosnippet-snippets
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # vim-snippets
repo = 'honza/vim-snippets'

[[plugins]] # go
repo = 'nsf/gocode'

[[plugins]] # ruby rsense
repo = 'Shougo/neocomplcache-rsense.vim'
hook_add = '''
  if !exists('g:neocomplcache_omni_patterns')
  let g:neocomplcache_omni_patterns = {}
  endif
  let g:neocomplcache_omni_patterns.ruby = '[^. *\t]\.\w*\|\h\w*::'
  autocmd FileType ruby setlocal omnifunc=rubycomplete#Complete

  "rsenseのインストールフォルダがデフォルトと異なるので設定
  let g:rsenseHome = expand("/usr/local/bin/rsense")
  let g:rsenseUseOmniFunc = 1
'''
