[[plugins]] # fugitive
repo = 'tpope/vim-fugitive'
hook_add = '''
  function! LightLineFugitive()
    try
      if expand('%:t') !~? 'Tagbar\|Gundo\|NERD' && &ft !~? 'vimfiler' && exists('*fugitive#head')
        let mark = ''  " edit here for cool mark
        let branch = fugitive#head()
        return branch !=# '' ? mark.branch : ''
      endif
    catch
    endtry
    return ''
  endfunction
'''

[[plugins]] # vim unite giti
repo = 'kmnk/vim-unite-giti'

[[plugins]] # gitでtigっぽいの
repo = 'cohama/agit.vim'
