[[plugins]] # toml
repo = 'cespare/vim-toml'

[[plugins]] # ruby
repo = 'vim-ruby/vim-ruby'

[[plugins]] # rails
repo = 'tpope/vim-rails'

[[plugins]] # slim
repo = 'slim-template/vim-slim'

[[plugins]] # elixir
repo = 'elixir-editors/vim-elixir'

[[plugins]] # go
repo = 'fatih/vim-go'
hook_add = '''
  let g:go_highlight_functions = 1
  let g:go_highlight_methods = 1
  let g:go_highlight_structs = 1
  let g:go_highlight_operators = 1
  let g:go_highlight_build_constraints = 1
  let g:go_fmt_fail_silently = 1
  let g:go_fmt_autosave = 0
'''

[[plugins]] # vue
repo = 'posva/vim-vue'

[[plugins]] # pug
repo = 'digitaltoad/vim-pug'
