[[plugins]] # unite
repo = 'Shougo/unite.vim'

[[plugins]] # vim-autoclose 自動閉じタグ
repo = 'yuroyoro/vim-autoclose'

[[plugins]] # 整形・桁揃えプラグイン
repo = 'junegunn/vim-easy-align'

[[plugins]] # コメントON/OFFを手軽に実行
repo = 'tomtom/tcomment_vim'

[[plugins]] # インデントの行対応をわかりやすく
repo = 'Yggdroot/indentLine'

[[plugins]] # 複数カーソル
repo = 'terryma/vim-multiple-cursors'
hook_add = '''
  " Called once right before you start selecting multiple cursors
  " https://github.com/spf13/spf13-vim/issues/1023
  function! Multiple_cursors_before()
    if exists(':NeoCompleteLock')==2
      exe 'NeoCompleteLock'
    endif
  endfunction

  " Called once only when the multiple selection is canceled (default <Esc>)
  function! Multiple_cursors_after()
    if exists(':NeoCompleteUnlock')==2
      exe 'NeoCompleteUnlock'
    endif
  endfunction
'''

[[plugins]] # 編集差分をハイライトする
repo = 'airblade/vim-gitgutter'

[[plugins]] # ペースト整形
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]] # ステータスラインをカスタマイズ
repo = 'itchyny/lightline.vim'

[[plugins]] # インデントの行対応をわかりやすく
repo = 'Yggdroot/indentLine'

[[plugins]] # Vimのテキストオブジェクトを拡張する
repo = 'tpope/vim-surround'

[[plugins]] # 自動で閉じる
repo = 'tpope/vim-endwise'

[[plugins]] # ステータスラインをカスタマイズ
repo = 'itchyny/lightline.vim'

[[plugins]] # インデントの行対応をわかりやすく
repo = 'Yggdroot/indentLine'

[[plugins]] # ファイルリネーム
repo = 'danro/rename.vim'

[[plugins]] # 複数行コメントアウト
repo = 'tyru/caw.vim.git'

[[plugins]] # コメントに#が用いられる
repo = 'tomtom/tcomment_vim'

[[plugins]] # シンタックスチェック
repo = 'osyo-manga/vim-watchdogs'

[[plugins]]
repo = 'christoomey/vim-tmux-navigator'
